#pragma once

#include <vector>

#include "vb/biorthogonal_vbscf/biorthogonal_orbital_integrals.hpp"
#include "vb/biorthogonal_vbscf/biorthogonal_selected_state_matrices.hpp"
#include "vb/matrices/cpp_vb_input.hpp"
#include "vb/orbital/active_space_two_electron_result.hpp"

namespace xmvb::vb::biorthogonal_vbscf {

/**
 * @brief Active-space adjoint induced by the exact biorthogonal 2e transform.
 *
 * This is the exact transform-layer contribution generated by the mixed
 * left/right active-space two-electron integrals
 *
 * `g^{bi}_{r_1 l_1 r_2 l_2}
 *   = sum_{a,b} X^{-1}_{a,l_1} X^{-1}_{b,l_2}
 *     G_{(r_1,a),(r_2,b)}`.
 *
 * The output contains:
 * - the packed active-space 2e gradient with respect to the original `GGO`
 *   storage,
 * - the induced overlap gradient from the two transformed left legs via
 *   `X^{-1} = SSO^{-1}`.
 *
 * This first implementation is an exact determinant-level reference path used
 * to validate the transform-layer algebra on `F2`. It does not yet perform the
 * final unique-spin / block-contracted optimization.
 */
struct BiorthogonalTwoElectronTransformBackwardContribution {
  std::vector<double> active_orbital_overlap_gradient;
  std::vector<double> packed_active_two_electron_gradient;
};

/**
 * @brief Builds the exact biorthogonal 2e transform contribution.
 *
 * `input.structure_data.alpha_det/beta_det` provide the full determinant
 * topology, `selected_state_matrices` provide the exact selected-state
 * determinant weights, `orbital_integrals.left_dual_from_right_transform`
 * stores `X^{-1}`, and `right_right_two_electron_result` supplies the original
 * active-space pair kernel `GGO`.
 */
BiorthogonalTwoElectronTransformBackwardContribution
build_biorthogonal_two_electron_transform_backward_contribution(
    const xmvb::vb::CppVbInput& input,
    const BiorthogonalSelectedStateMatrices& selected_state_matrices,
    const BiorthogonalOrbitalIntegrals& orbital_integrals,
    const xmvb::vb::ActiveSpaceTwoElectronResult& right_right_two_electron_result);

}  // namespace xmvb::vb::biorthogonal_vbscf
