#pragma once

#include <vector>

#include "vb/biorthogonal_vbscf/biorthogonal_orbital_integrals.hpp"
#include "vb/biorthogonal_vbscf/biorthogonal_selected_state_matrices.hpp"
#include "vb/matrices/same_spin_pair_cache.hpp"

namespace xmvb::vb::biorthogonal_vbscf {

/**
 * @brief Active-space adjoint induced by the exact biorthogonal 1e transform.
 *
 * This is the part of the exact-selected active-space backward generated by the
 * explicit one-electron transform
 *
 * `h^{LR} = X^{-1} HHO`,
 * `X^{-1} = SSO^{-1}`.
 *
 * The contribution is computed in two steps:
 * 1. accumulate `dE / d h^{LR}` from the exact biorthogonal selected-state
 *    `L/R` amplitudes on the ordered unique alpha/beta spin pairs,
 * 2. pull that adjoint back to the original active-space one-electron matrix
 *    `HHO` and overlap matrix `SSO`.
 */
struct BiorthogonalOneElectronTransformBackwardContribution {
  std::vector<double> active_orbital_overlap_gradient;
  std::vector<double> active_one_electron_gradient;
};

/**
 * @brief Builds the exact biorthogonal one-electron transform contribution.
 *
 * `same_spin_pair_cache` is used only for the ordered unique-spin topology,
 * namely the unique alpha/beta spin strings and the determinant-to-unique id
 * maps already shared by the exact-selected matrix-form path.
 *
 * `orbital_integrals.left_dual_from_right_transform` stores `X^{-1}`, while
 * `right_right_one_electron` stores the current active-space `HHO` in
 * column-major `(n_orbitals, n_orbitals)` storage.
 */
BiorthogonalOneElectronTransformBackwardContribution
build_biorthogonal_one_electron_transform_backward_contribution(
    const xmvb::vb::SameSpinPairCacheContext& same_spin_pair_cache,
    const BiorthogonalSelectedStateMatrices& selected_state_matrices,
    const BiorthogonalOrbitalIntegrals& orbital_integrals,
    const std::vector<double>& right_right_one_electron);

}  // namespace xmvb::vb::biorthogonal_vbscf
