#!/bin/bash
FILE="/pool1/home/xiatao/project/xmvb-cpp/src/vb/scf/cpp_vb_scf_optimizer.cpp"
echo "Searching for terms in $FILE"
echo "===================================="
echo ""
echo "1. full_retry_ready:"
grep -n "full_retry_ready" "$FILE" || echo "Not found"
echo ""
echo "2. full_model_correction_allowed:"
grep -n "full_model_correction_allowed" "$FILE" || echo "Not found"
echo ""
echo "3. inner_solve_uses_outer_response:"
grep -n "inner_solve_uses_outer_response" "$FILE" || echo "Not found"
echo ""
echo "4. model_quality_full_retry:"
grep -n "model_quality_full_retry" "$FILE" || echo "Not found"
echo ""
echo "5. request_followup:"
grep -n "request_followup" "$FILE" || echo "Not found"
echo ""
echo "6. exact_ctx_retry_rejected:"
grep -n "exact_ctx_retry_rejected" "$FILE" || echo "Not found"
