#pragma once

#include <Eigen/Core>

#include <vector>

#include "vbscf/determinants/same_spin_pair_cache.hpp"
#include "vbscf/derivatives/hessian/responses/active_space_direction.hpp"
#include "vbscf/integrals/active/active_space_two_electron_result.hpp"
#include "vbscf/structures/selected_state_coefficients.hpp"

namespace xmvb::vb {

/**
 * @brief Matrix-form same-spin / one-electron backward contribution.
 *
 * This object contains the part of the active-space adjoint generated by the
 * separable channels
 *
 * `H_alpha * S_beta + S_alpha * H_beta`
 *
 * where `H_sigma` here includes the same-spin one- and two-electron
 * determinant Hamiltonian of a single spin sector.
 */
struct SameSpinMatrixBackwardContribution {
  std::vector<double> active_orbital_overlap_gradient;
  std::vector<double> active_one_electron_gradient;
  std::vector<double> packed_active_two_electron_gradient;
};

/** Directional polynomial data for one ordered unique-spin determinant pair. */
struct SameSpinPolynomialDirectionalPairData {
  double delta_overlap_determinant = 0.0;
  double delta_total_hamiltonian = 0.0;
  Eigen::MatrixXd cofactor_1st;
  Eigen::MatrixXd delta_cofactor_1st;
  Eigen::MatrixXd delta_same_spin_overlap_hamiltonian_gradient;
};

/**
 * Directional pair data and scalar matrices shared by all outer-response
 * consumers in one matrix-free Hessian application.
 */
struct SameSpinDirectionalScalarMatrices {
  Eigen::MatrixXd delta_overlap_determinant_matrix;
  Eigen::MatrixXd delta_regular_total_hamiltonian_matrix;
  Eigen::MatrixXd delta_singular_total_hamiltonian_matrix;
  std::vector<SameSpinPolynomialDirectionalPairData> ordered_pair_data;
};

struct SameSpinDirectionalPairCache {
  SameSpinDirectionalScalarMatrices alpha;
  SameSpinDirectionalScalarMatrices beta;
  bool close_shell_same_spin = false;
};

SameSpinDirectionalPairCache build_same_spin_directional_pair_cache(
    const SameSpinPairCacheContext& same_spin_pair_cache,
    int n_active_orbitals,
    const ActiveSpaceIntegralDirectionView& direction);

/**
 * @brief Builds matrix-form same-spin / one-electron backward contribution.
 *
 * This routine requires:
 * 1. an enabled same-spin pair cache,
 * 2. populated same-spin `phi` cache entries on the regular ordered unique
 *    same-spin determinant pairs that carry selected-state weight.
 *
 * The implementation works directly on the selected-state unique-spin
 * coefficient matrices `C^(n)` and contracts the separable same-spin channels
 * with dense products on the unique alpha/beta spaces, e.g.
 *
 * `C^(n) B_beta [C^(n)]^T` and `[C^(n)]^T A_alpha C^(n)`,
 *
 * before scattering the resulting ordered unique-pair weights back to the AO
 * overlap / one-electron / same-spin two-electron gradients.
 *
 * `selected_state_energies[k]` must align with `selected_states.states[k]`.
 */
SameSpinMatrixBackwardContribution build_same_spin_matrix_backward_contribution(
    const SameSpinPairCacheContext& same_spin_pair_cache,
    const SelectedStateDeterminantMatrices& selected_states,
    const std::vector<double>& selected_state_energies,
    int n_active_orbitals);

/**
 * @brief Builds the directional same-spin backward contribution.
 *
 * This is the exact linear response of the matrix-form same-spin backward to a
 * selected-state response
 *
 * `C^(n) -> C^(n) + \delta C^(n)`
 * `E_n -> E_n + \delta E_n`
 *
 * while the accepted-point same-spin cache payloads remain fixed. The output
 * therefore represents the outer-response part that must be added to the
 * accepted-point orbital Hessian-vector product after the generalized
 * eigensystem has been differentiated.
 */
SameSpinMatrixBackwardContribution
build_directional_same_spin_matrix_backward_contribution(
    const SameSpinPairCacheContext& same_spin_pair_cache,
    const SelectedStateDeterminantMatrices& selected_states,
    const SelectedStateDeterminantMatrices& directional_selected_states,
    const std::vector<double>& selected_state_energies,
    const std::vector<double>& directional_selected_state_energies,
    int n_active_orbitals);

/**
 * @brief Builds the same-spin local-response contribution in matrix form.
 *
 * This is the exact `\delta J_{\mathrm{same}}^T \lambda` term where the
 * accepted-point selected-state weights stay fixed and only the same-spin
 * determinant kernels respond to the active-space direction
 *
 * `(\delta S_{\mathrm{act}}, \delta h_{\mathrm{act}}, \delta g_{\mathrm{act}})`.
 *
 * The routine compresses the accepted structure/determinant adjoints onto the
 * unique alpha/beta spaces exactly as in the accepted-point same-spin backward,
 * then differentiates the local same-spin pair kernels on the unique-spin
 * channels instead of revisiting every determinant pair.
 */
SameSpinMatrixBackwardContribution
build_local_same_spin_matrix_backward_contribution(
    const SameSpinPairCacheContext& same_spin_pair_cache,
    const SelectedStateDeterminantMatrices& selected_states,
    const std::vector<double>& selected_state_energies,
    int n_active_orbitals,
    const Eigen::Ref<const Eigen::MatrixXd>& active_one_electron_matrix,
    const ActiveSpaceTwoElectronResult& active_space_two_electron_result,
    const ActiveSpaceIntegralDirectionView& direction,
    const SameSpinDirectionalPairCache& directional_pair_cache);

}  // namespace xmvb::vb
